### ISSUE TITLE
Concurrent commit IsolatePath type env in root_state, system memory leak

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#159]
**Describe the bug**
Concurrent commit IsolatePath type env in root_state, system memory leak

**To Reproduce**
Each op_env inserts 1000 key values, and 100 concurrent op_env.commit() operations, the system memory overflows and is not released after the commit success
```
                       let create_result = await stack.root_state_stub().create_isolate_path_op_env_with_access({
                            access :cyfs.AccessPermissions.Full,
                            path : env_path
                        });
                        let op_env =  create_result.unwrap();
                        let create_info =await op_env.create_new(cyfs.ObjectMapSimpleContentType.Map)
                        assert.ok(!create_info.err);
                        let object_list = [];
                        for (let j = 0; j < ket_data_number; j++) {
                            let id = `message-${RandomGenerator.string(20)}-${Date.now()}`;
                            let request_json = JSON.stringify({
                                message: RandomGenerator.string(20)
                            });
                            let begin = Date.now();
                            let save_object = HandlerRequestObject.create(stack.local_device_id().object_id, HandlerType.PutObject, id,request_json, new Uint8Array(0));
                            let create_time = Date.now() - begin;
                            let result = await stack.non_service().put_object({
                                common: {
                                    flags: 1,
                                    level: cyfs.NONAPILevel.NOC
                                },
                                object: cyfs.NONObjectInfo.new_from_object_raw(save_object.to_vec().unwrap()).unwrap(),
                            })
                            let put_time = Date.now() - begin - create_time;
                            assert.ok(!result.err)
                            assert.ok(!result.err)
                            let object_id = save_object.calculate_id().to_base_58()
                            logger.info(`task ${i} put object success ${object_id} ,create_time = ${create_time} put_time = ${put_time}`)
                            let object_path =  `${env_path}/${object_id}`;
                            let insert_root =await op_env.insert_with_key(object_path,
                                object_id,
                                save_object.calculate_id(),)
                            assert.ok(!insert_root.err);
                            object_list.push({
                                object_path,
                                key : object_id,
                                object_id,
                                id,
                                request_json,
                                create_time,
                                put_time
                            })
                        }
                        let commit =await op_env.commit();
```

**Expected behavior**
The overall size of 100,000 key values is only about 40MB, OOD consumes about 69%*4GB=2.8GB of memory, and there should be memory overflow in the op_env.commit operation of CYFS Stack

**System information**
Linux OOD 
4GB memory

**Comment by lurenpluto** [comment]
Regarding the optimization of this case, I built two features about optimization as follows

- [ ] #193 
- [ ] #194

Welcome to pay attention to relevant progress!

**Comment by lurenpluto** [comment]
> **Describe the bug** Concurrent commit IsolatePath type env in root_state, system memory leak
> 
> **To Reproduce** Each op_env inserts 1000 key values, and 100 concurrent op_env.commit() operations, the system memory overflows and is not released after the commit success
> 
> ```
> ```
> 
> **Expected behavior** The overall size of 100,000 key values is only about 40MB, OOD consumes about 69%*4GB=2.8GB of memory, and there should be memory overflow in the op_env.commit operation of CYFS Stack
> 
> **System information** Linux OOD 4GB memory

In addition, during the above test case process, I did not find any memory leak phenomenon. After the commit operation of op-env is completed, the memory usage will decrease to the previous level. However, the performance of the commit operation will be poor under the 100 concurrent situations, which takes a long time.

From the test, memory usage can be divided into three stages:

https://github.com/buckyos/CYFS/blob/1cb0c9657243dcdec3cd9db89f392b0a8bf600ef/src/component/cyfs-base/src/objects/object_map/isolate_path_env.rs#L361-L374

- After the completion of the 1000 operations in op-env and before commit, memory usage reaches its maximum.
- During the internal garbage collection (GC) of op-env's commit, all temporary objects are reclaimed, and memory usage is significantly reduced.
- After the commit operation of op-env is completed, the memory usage returns to the level before running the test case (this process takes a longer time).


So, in your test case, the "memory leak" may be due to op-env not having completed the commit operation, or it could be a side effect caused by other factors introduced in the test case.
