### ISSUE TITLE
After deploy DecApp sucess, Install DecApp failed for not found version

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#195]
**Describe the bug**
CYFS App Install Link: cyfs://5r4MYfFJ7ktzBzSi1sWmU7BJLgpEEdp8ukbWemsFuQc1/9tGpLNnH1nXE3Ku2CgrQuc3JggtJuvAM3sP3Ype33qSv

My OOD  Installed DecApp  9tGpLNnH1nXE3Ku2CgrQuc3JggtJuvAM3sP3Ype33qSv version 1.0.0, then I deploy 9tGpLNnH1nXE3Ku2CgrQuc3JggtJuvAM3sP3Ype33qSv version 1.0.1，I updated the latest version 1.0.1 in the CYFS browser, but the DEC APP installation failed

**To Reproduce**
+ Installed 9tGpLNnH1nXE3Ku2CgrQuc3JggtJuvAM3sP3Ype33qSv version 1.0.0
+ cyfs delpoy 9tGpLNnH1nXE3Ku2CgrQuc3JggtJuvAM3sP3Ype33qSv  version 1.0.1
+ Install  9tGpLNnH1nXE3Ku2CgrQuc3JggtJuvAM3sP3Ype33qSv  version 1.0.1, run execption
```
[2023-04-11 19:39:18.843035 +08:00] ERROR [ThreadId(6)] [service/app-manager/src/app_controller.rs:137] app:9tGpLNnH1nXE3Ku2CgrQuc3JggtJuvAM3sP3Ype33qSv cannot find source for ver 1.0.1, err: err: (NotFound, , None)
```
**System information**
OOD-Service : current version: 1.1.0.746-nightly (23-04-10)
[cyfs_log_gateway_appmanager.zip](https://github.com/buckyos/CYFS/files/11200025/cyfs_log_gateway_appmanager.zip)

**Comment by weiqiushi** [comment]
CYFS protocol stack in recent versions, in order to reduce the pressure on the meta chain nodes, introduced a caching mechanism for fetching objects from the meta chain:

When the last operation of fetching the same object (based on the object Id) from the meta chain is less than a certain time interval, the cached object inside the stack is returned directly. Currently, this time interval is 10 minutes.

As DecApp is installed, AppManager passes CYFS_ROUTER_REQUEST_FLAG_FLUSH flag through the get_object interface of the protocol stack to get the new DecApp object from the meta chain through the protocol stack. This logic is also influenced by the caching policy of the protocol stack

Recommended action: After publishing the App, wait for 10 minutes before trying to install it. If in a test environment, you can reset the memory cache of the protocol stack by restarting the gateway process
