### ISSUE TITLE
Panic when start `cyfs-meta-genesis` in `Debug`

### ISSUE THREAD

**Issue by streetycat** [buckyos/CYFS#199]
thread 'main' has overflowed its stack

**Comment by streetycat** [comment]
The closure in `async_std::task::block_on` is too large for stack, put it in heap with `Box`.

**Comment by lurenpluto** [comment]
This phenomenon is easy to occur when running services and tools in debug mode.

In most cases, you need to compile the release version and then run itIn most cases, you need to compile the release version and then run it

**Comment by streetycat** [comment]
> This phenomenon is easy to occur when running services and tools in debug mode.
> 
> In most cases, you need to compile the release version and then run itIn most cases, you need to compile the release version and then run it

Yes, I've found some solutions:
1. Move the large closure in heap from stack.
2. Cut the large function into little. **But I don't known how it works, anyone tell me?**

**Comment by lurenpluto** [comment]
> > This phenomenon is easy to occur when running services and tools in debug mode.
> > In most cases, you need to compile the release version and then run itIn most cases, you need to compile the release version and then run it
> 
> Yes, I've found some solutions:
> 
> 1. Move the large closure in heap from stack.
> 2. Cut the large function into little. **But I don't known how it works, anyone tell me?**

It seems that we can approach this from two perspectives:

1. Reduce the size of the data stored on the stack, for example by using heap instead of stack.
2. Switch threads, especially for some deep calls. If it can be completed among multiple threads, it should be better, such as using spawn_task.

Unless debugging is needed in the debug version, it can be run directly in release mode to avoid this.
