### ISSUE TITLE
Get DEC APP status timeout error not passed correctly

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#208]
**Describe the bug**
App-manager get DEC APP  status timeout ,The APP`s status  is always Starting. Should modify the APP`s status RunExpectation in this scenario?

**To Reproduce**
+ Install dec-app-command-wait2min cyfs://5r4MYfFJ7ktzBzSi1sWmU7BJLgpEEdp8ukbWemsFuQc1/9tGpLNndpfRjUF59SsZidVaPuPd8QNFJusQKH8genY3Q
+ This DEC APP I set node service.js --status return after 2 min ,It maybe run timeout
+ Then my APP`s status  is always Starting
```
[2023-04-13 20:39:19.639437 +08:00] INFO [ThreadId(34)] [service\app-manager\src\dapp.rs:194] run cmd node service/service.js --status in C:\cyfs\app\9tGpLNndpfRjUF59SsZidVaPuPd8QNFJusQKH8genY3Q
[2023-04-13 20:39:19.640994 +08:00] INFO [ThreadId(34)] [service\app-manager\src\dapp.rs:196] program full path: C:\Program Files\nodejs\node.exe
[2023-04-13 20:39:34.644448 +08:00] ERROR [ThreadId(34)] [service\app-manager\src\dapp.rs:324] process not exit after timeout, app:dec-app-service, cmd:node service/service.js --status
```
**Expected behavior**
If app-manager get DEC APP`s staus timeout ,This DEC APP may be run expection, Should modify the APP`s status RunExpectation 

[app-manager_get_status_timout.zip](https://github.com/buckyos/CYFS/files/11228738/app-manager_get_status_timout.zip)

**Comment by weiqiushi** [comment]
Unlike the install command, the status command ***should*** be controllable. This is the basic requirement of AppManager for DecApp developers.

If the status command does not return after a period of time (the current logic is 15 seconds, and this value may change later), AppManager will consider the command as an error.
At this time, the status of App is unknown and waiting for the next check to determine the status of App

**Important**: If the status command is wrong, it does not necessarily mean that the dec service is wrong, and it should not enter the RunException state at this time, because this state indicates the running state of the dec service.

If the status keeps on being wrong, which causes AppManager not to correctly respond to the state of the dec service, the developer has the obligation to fix the problem.

**Comment by lizhihongTest** [comment]
In this scenario, app-manager run CmdCOde::Status has caught the exception, and app-manager should pass the error to the developer through the external interface. Currently, it is normal for app-manager to return the external status, which can only be passed through the log of app-manager to find abnormalities. It is impossible to ask the developer to check the app-manager log to locate the problem.

**Comment by weiqiushi** [comment]
First of all, there is no such operation request as CmdCode::Status. the App's status command is only called by the AppManager to determine the status internally. This status is not returned to the user directly, but only used for AppManager's internal logic.

Secondly, we believe that a normal DecApp developer should do some basic tests locally before the App hits the shelves. And these tests should ensure whether the basic commands of start, status, stop are running as required.

Currently, AppManager is focused on providing the right and appropriate functions to run DecApp. There are no plans to optimize the DecApp development experience.

Finally, AppManager is not obligated to help unqualified DecApp developers ensure that their DecApps run as well as possible. The 15-second timeout for the status command is just an internal insurance measure for AppManager to ensure that unqualified DecApps do not bring down the normal functionality of AppManager.

**Comment by weiqiushi** [comment]
This idea can be compared to the Windows "window unresponsiveness" feature, where windows does not tell the developer under what conditions a program stuck in the main thread will be judged as "unresponsive"
