### ISSUE TITLE
AppManager's _force_stop logic may kill other processes by mistake

### ISSUE THREAD

**Issue by weiqiushi** [buckyos/CYFS#225]
In the code of AppManager, there is the following logic:

https://github.com/buckyos/CYFS/blob/580816c558304f941fce35f891ad77aee928a71b/src/service/app-manager/src/dapp.rs#L454-L456

When stopping DecApp, if the status command is called and returns that the current DecApp is not running, _force_stop will be called to use the process ID recorded before and force kill the process.
However, in the docker environment, since the pid assigned by the system are small, when _force_stop uses the old pid, it may kill the newly started process. The following logs may illustrate this situation:

[ood-daemon_7_rCURRENT(4).log](https://github.com/buckyos/CYFS/files/11269740/ood-daemon_7_rCURRENT.4.log)
[app-manager_32_rCURRENT(1).log](https://github.com/buckyos/CYFS/files/11269741/app-manager_32_rCURRENT.1.log)

The user has OOD running inside a docker container and on restarting the container:
AppManager starts, and restarts all DecApps. restart is implemented by calling stop and then start for each DecApp. when stop is called, status is called first to determine whether the process is started, and _force_stop is called when the status command returns 0, indicating that the process is not started. at this time The gateway process that has just been started may be killed by mistake, because the process ID assigned by docker is the same as the one assigned to DecApp before.

According to the principle, when the status command returns 0, it means that the DecApp process is not started, so why does it call _force_stop at this time?

@glen0125

**Comment by glen0125** [comment]
Force stop is to ensure that the app is stopped. If it is confirmed that the app is not running, force stop can be removed, and it 
SHOULD BE removed based on the above situation.

**Comment by lurenpluto** [comment]
If there is really a need to add a strategy to force kill the target dec app process based on pid, then in general you need to add some secondary verification mechanism to ensure that the pid belongs to the dec-app to avoid being killed by mistake

## 1. Check by the app's start command line
app-manager knows the command line of the corresponding app, so it can check whether the command line matches; but since the start command line of different apps may be the same (for example, some nodejs-based apps), there may be a case of misjudgment
	
## 2. Improve the app launch command line to improve the distinction
When each app is launched, force some parameters to be added, such as `-app-id xxx`, so that the distinction can be forced by the command line; the disadvantage is that the developer specification of the app needs to be changed to require the app to handle the command line without making mistakes for these extra default command lines
	
## 3. Using working directory (CWD)
At present, every app is forced to set the current working directory as the app installation directory when it is launched, and this directory has app-id information, so there is enough distinction
	
	There is a little bit of trouble, that is, you need to do different processing for windows and nix platform, to ensure that the corresponding CWD can be obtained through the pid
	
In comparison, I feel that the third model maybe is more perfect

**Comment by weiqiushi** [comment]
I think I can use crate [sysinfo](https://docs.rs/sysinfo/latest/sysinfo/index.html) to get process's cwd. I already wrote a simple demo and it can get processes's cwd and cmd in both Windows and Linux(Ubuntu)

```rust
    let matches = clap::Command::new("workdir").arg(Arg::new("pid").value_parser(value_parser!(u32)).index(1).required(true)).get_matches();

    let pid: u32 = *matches.get_one("pid").unwrap();

    let info = sysinfo::System::new_with_specifics(RefreshKind::new().with_processes(ProcessRefreshKind::new()));
    let proc = info.process(Pid::from_u32(pid)).unwrap();
    println!("process {} cwd {}, command {}", pid, proc.cwd().display(), proc.cmd().join(" "))
```
