### ISSUE TITLE
After App-manager restarted the DEC APP installation process, the DEC APP was not started

### ISSUE THREAD

**Issue by lizhihongTest** [buckyos/CYFS#238]
**Describe the bug**
After App-manager restarted the DEC APP installation process, the DEC APP was not started

**To Reproduce**
+ Install dec-app cyfs://5r4MYfFJ7ktzBzSi1sWmU7BJLgpEEdp8ukbWemsFuQc1/9tGpLNnPZPoULTFVB6tbzrLkHS564isyc54PmWuNW6DT
+ When DEC APP is downloading files, kill the app-manager process
+ When the app-manager is restarted by ood-daemon,Check the result of this app`status.

**Expected behavior**
+ The app-manager reinstall 9tGpLNnPZPoULTFVB6tbzrLkHS564isyc54PmWuNW6DT sucesss,but not start this DEC APP service.

**System information**
Nighlty ： 1.1.0.753-preview
OOD System : cyfs-test-lab::PC-0005(Ubuntu22)

[app-manager_261428_rCURRENT.log](https://github.com/buckyos/CYFS/files/11303240/app-manager_261428_rCURRENT.log)
[app-manager_143230_rCURRENT.log](https://github.com/buckyos/CYFS/files/11303242/app-manager_143230_rCURRENT.log)

**Comment by weiqiushi** [comment]
This is due to the fact that the previous developer handled the startup status repair logic in parallel with the command execution logic:

Since in the old code, the startup status repair was fast, just set to Failed, in most cases, the startup status was repaired before the first command was executed

However, in the new logic, the action indicated by the startup status will be executed again, which may be more time-consuming. If the Start command is executed in the startup state repair, this Start command will be skipped because DecApp is still in the wakeup state

**Comment by weiqiushi** [comment]
When App Manager starts, instead of executing the corresponding repair logic directly, the corresponding command is inserted into the internal cmdlist from the front end

This will make DecApp's state repair time longer, but will not cause the state error problem caused by parallel execution of repair

**Comment by lizhihongTest** [comment]
This Issue has been fixed in Nighlty 1.1.0.754
