### ISSUE TITLE
cyfs-stack support NO-SN online

### ISSUE THREAD

**Issue by waterflier** [buckyos/CYFS#56]
**The purpose of the feature**
If My device have statice-wan address(IPv4 or IPv6),I can let the EndPoint info on-chain and donn't need SN anymore.

**Describe the solutions to the feature you'd like**
cyfs-stack support NO-SN online

**Comment by lurenpluto** [comment]
Currently, for OODs with a fixed public IP address (such as vood), the following mechanisms are in place to ensure maximum connectivity:

- When activating the OOD, the WAN address and port are added to the OOD's device and registered on the blockchain. This way, when the protocol stack connects to the target device, it will prioritize using the WAN address and port configured in the device.

- The gateway configuration on the OOD does not need to be explicitly changed, meaning the SN stays online. However, when the protocol stack starts, SN online status no longer blocks the stack startup (e.g., if there's some wrong with the SN server, the protocol stack will not be unable to start due to SN.wait_online). When necessary, connections will be initiated through SN.

- When connecting to the target device with a configured WAN address, the protocol stack will first try to establish a direct connection using the WAN address. If it fails, it will attempt to connect again through the SN (if the device remains online on SN) and acquire the latest device for future use.

- If the protocol stack fails to establish a connection using the device, it will try to update the information from the metachain once (for both the device and its owner). This is mainly to handle the following two possible changes:

1. The device's WAN address has changed, such as an external IP address change, and other devices' local cache is outdated compared to the metachain.
2. The owner's OOD list has changed, for example, if the device is no longer an OOD for the target zone. In this case, after updating the owner's information, the corresponding zone information needs

**Comment by lurenpluto** [comment]
Complete at 1c4a58886bad3ba65552ef41ac4748316d874a18
